language: python

python:
- "2.7"

#install:
#- pip install cheetah
#- pip install twisted
#- pip install pyopenssl

script: 
#- python -m compileall -l . -l plugin -l plugin/backport -l plugin/controllers -l plugin/controllers/models
#- cheetah compile -R plugin
- ls

after_success:
- ./create_ipk.sh

deploy:
  provider: releases
  api_key: "GITHUB OAUTH TOKEN"
  file: "${PKG}"
  skip_cleanup: true
  on:
    tags: true
    deploy:
