language: python

python:
- "2.7"

#install:
#- pip install cheetah
#- pip install twisted
#- pip install pyopenssl

script: 
#- python -m compileall -l . -l plugin -l plugin/backport -l plugin/controllers -l plugin/controllers/models
#- cheetah compile -R plugin
- ls

after_success:
- ./create_ipk.sh
- echo ${PKG}

deploy:
  provider: pages
  api_key: "db6c21dfcc771a6d93b8dcb5e22781e75edbb844"
  file: "${PKG}"
  skip_cleanup: true
  target_branch: gh-pages
  on:
    branch: master
