language: python

python:
- "2.7"
- "3.8"

matrix:
  include:      
    - name: "Python 2.7"
      before_install:
        - sudo apt-get install -y closure-compiler nodejs npm
        - "npm config set strict-ssl false"
        - sudo npm install -g jshint
        - pip install Cheetah
        - pip install -r requirements.txt
        - pip install bandit
      script:
        - python -m compileall -l . -l plugin -l plugin/backport -l plugin/controllers -l plugin/controllers/models
        - cheetah compile -R plugin
        - python testsuite/evil_eval.py
        - futurize --stage1 **/*.py
        - futurize --stage2 **/*.py
        #- 2to3 -f all .
      after_success:
        - bandit -r plugin -f html -o bandit.html
        - python -m flake8 --ignore=W191,E501,E302 plugin/ --output-file flake8_report.txt
        - jshint ./sourcefiles/js/ | tee jshint1_report.txt
        - jshint ./sourcefiles/themes/absb/js/ | tee jshint2_report.txt
        - ./create_ipk.sh
        - export PKG=$(ls -1 *.ipk)
        - mkdir Rel
        - touch ./Rel/.nojekyll
        - mv "${PKG}" ./Rel
        - mv bandit.html ./Rel
        - mv flake8_report.txt ./Rel
        - mv jshint1_report.txt ./Rel
        - mv jshint2_report.txt ./Rel
        #- if [[ $TRAVIS_PYTHON_VERSION == 2.7.15 ]]; then mv 2to3.txt ./Rel; fi
        #- if [[ $TRAVIS_PYTHON_VERSION == 2.7.15 ]]; then mv futurize_stage1.txt ./Rel; fi
        - cd doc
        - make html
        - cd build/html
        - mv * ../../../Rel/
      
    - name: "Python 3.8"
      before_install:
        - pip install Cheetah3
      script:
        - python -m compileall -l . -r 10 -q
        - cheetah compile -R plugin
        - python testsuite/evil_eval.py

deploy:
  provider: pages
  local_dir: Rel
  github_token: $GITHUB_TOKEN
  skip_cleanup: true
  target_branch: gh-pages
  on:
    branch: master
    condition: $TRAVIS_PYTHON_VERSION = 2.7.15
