name: e2openplugin-OpenWebif

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: 'master'

      - uses: actions/setup-python@v2
        with:
          python-version: '2.7'

      - name: Build python 2.7
        run: |
          sudo apt-get install -y closure-compiler nodejs npm
          "npm config set strict-ssl false"
          sudo npm install -g jshint
          pip install Cheetah
          pip install -r requirements.txt
          pip install bandit==1.6.2
          pip install six
          python -m compileall -l . -l plugin -l plugin/backport -l plugin/controllers -l plugin/controllers/models
          cheetah compile -R plugin
          python testsuite/evil_eval.py

      - uses: actions/checkout@v2
        with:
          ref: 'master'

      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Build python 3.8
        run: |
          pip3 install Cheetah3
          pip3 install six
          pip install --upgrade pip autopep8
          python -m compileall -l . -r 10 -q
          cheetah compile -R plugin
          python testsuite/evil_eval.py
