name: e2openplugin-OpenWebif-python2

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: 'master'

      - uses: actions/setup-python@v2
        with:
          python-version: '2.7'

      - name: Build python 2.7
        run: |
          sudo apt-get install -y closure-compiler nodejs npm
          sudo npm install -g jshint
          pip install Cheetah
          pip install -r requirements.txt
          pip install bandit==1.6.2
          pip install six
          python -m compileall -l . -l plugin -l plugin/backport -l plugin/controllers -l plugin/controllers/models
          cheetah compile -R plugin
          python testsuite/evil_eval.py
          bandit -r plugin -f html -o bandit.html || true
          python -m flake8 --ignore=W191,E501,E302 plugin/ --output-file flake8_report.txt || true
          jshint ./sourcefiles/js/ | tee jshint1_report.txt
          jshint ./sourcefiles/modern/js/ | tee jshint2_report.txt
          mkdir Rel
          touch ./Rel/.nojekyll
          mv bandit.html ./Rel
          mv flake8_report.txt ./Rel
          mv jshint1_report.txt ./Rel
          mv jshint2_report.txt ./Rel
          cd doc
          make html
          cd build/html
          mv * ../../../Rel/

      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: Rel
