name: TEST

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: 'master'
          fetch-depth: 0

      - uses: actions/setup-python@v2
        with:
          python-version: '2.7'

      - name: Build python 2.7
        run: |
          git rev-list HEAD --since=yesterday --count
          git rev-list HEAD --since=today --count
          git rev-list HEAD

